### ISSUE TITLE
Battlehawks 1942

### ISSUE THREAD

**Issue by Burrito78** [TotalDOSCollection/TDCbugs#11]
Filename:
Battlehawks 1942 [a1] (1988)(Lucasfilm Games) [Action, Simulation].zip

Issue:
According to @aaronsgiles this is a hacked/cracked version of the game.

![Bildschirmfoto 2024-06-23 um 14 49 18](https://github.com/TotalDOSCollection/TDCbugs/assets/61995128/5159a471-5999-4a34-b152-77784bb79e1e)

**Comment by TotalDOSCollection** [comment]
It's a different crack than what we have, so I've documented it in case it's ever needed.

`Deleted:Battlehawks 1942 [a1] (1988)(Lucasfilm Games) [Action, Simulation].zip-->dif crack, not needed.`

STDV1S.PAC is also corrupt in that archive.
Related:
```
Renamed:Battlehawks 1942 (1988)(Lucasfilm Games) [kfx][360k][!].zip-->Battlehawks 1942 v1.0 (1988)(Lucasfilm Games) [kfx][360k][!].zip
Renamed:Battlehawks 1942 (1988)(Lucasfilm Games) [IMA][360k][!].zip-->Battlehawks 1942 v1.0 (1988)(Lucasfilm Games) [IMA][360k][!].zip

```
Thanks for the report!
