### ISSUE TITLE
Indiana Jones and the Temple of Doom (1989)

### ISSUE THREAD

**Issue by Burrito78** [TotalDOSCollection/TDCbugs#13]
Filenames:
Indiana Jones and the Temple of Doom (1989)(Mindscape, Inc.) [Action].zip
Indiana Jones and the Temple of Doom [a1] (1989)(Mindscape, Inc.) [Action].zip
Indiana Jones and the Temple of Doom [a2] (1989)(Mindscape, Inc.) [Action].zip

Issues:
a1 version is an original version, the other two have the copy protection hacked out.

![Bildschirmfoto 2024-06-24 um 16 40 42](https://github.com/TotalDOSCollection/TDCbugs/assets/61995128/a90cb5a3-73a8-46b5-af8c-cf42ec018be8)

**Comment by TotalDOSCollection** [comment]
My take on this one:
Indiana Jones and the Temple of Doom (1989)(Mindscape, Inc.) [Action].zip - indy.exe has corruption 293b0->293ff
Indiana Jones and the Temple of Doom [a2] (1989)(Mindscape, Inc.) [Action].zip - compressed with pklite, matches feb 89 once removed.

re-pulled+re-cracked files from both IMAs.
added IMA files.

So we now have two IMA files and two versions of the game, all others are in the junk pile for tracking only.
Added:Indiana Jones and the Temple of Doom r890516 (1989)(Mindscape, Inc.) [IMA][360k].zip
Added:Indiana Jones and the Temple of Doom r890516 (1989)(Mindscape, Inc.) [Action].zip
Added:Indiana Jones and the Temple of Doom r890224 (1989)(Mindscape, Inc.) [IMA][360k].zip
Added:Indiana Jones and the Temple of Doom r890224 (1989)(Mindscape, Inc.) [Action].zip
