### ISSUE TITLE
Night Shift (1990)

### ISSUE THREAD

**Issue by Burrito78** [TotalDOSCollection/TDCbugs#15]
File:
Night Shift v1.1 [a1] (1990)(Lucasfilm Games LLC) [Action].zip

Issue:
Copy protection hacked out

![Bildschirmfoto 2024-06-24 um 16 50 21](https://github.com/TotalDOSCollection/TDCbugs/assets/61995128/04cc168e-09bb-488b-991a-5dbae1aab82f)

**Comment by TotalDOSCollection** [comment]
This has been sourced to an INC scene release.  It's a unique build of IML.EXE and thus doesn't match any source from floppy disk that has been found yet.  We've no mechanism to discover what was modified to remove the protection.  There's nothing to be done here until an original source is found.

Related, I did rename a few things and clean up some wiki entries for this title.

Closed as can't fix.  Will certainly fix if an original source is ever located.
