### ISSUE TITLE
Their Finest Hour - The Battle of Britain (1989)

### ISSUE THREAD

**Issue by Burrito78** [TotalDOSCollection/TDCbugs#19]
Files:
Their Finest Hour- The Battle of Britain (1989)(Lucasfilm Games LLC) [Action, Simulation].zip
Their Finest Hour- The Battle of Britain [a1] (1989)(Lucasfilm Games LLC) [Action, Simulation].zip
Their Finest Hour- The Battle of Britain [a2] (1989)(Lucasfilm Games LLC) [Action, Simulation].zip
Their Finest Hour- The Battle of Britain [a3] (1989)(Lucasfilm Games LLC) [Action, Simulation].zip

Issues:
Various, see screenshot.

![Bildschirmfoto 2024-06-25 um 14 55 36](https://github.com/TotalDOSCollection/TDCbugs/assets/61995128/fdb5a53f-b5b3-4943-a384-36d2b808b336)

**Comment by TotalDOSCollection** [comment]
Thanks for the cleanup notice.
`Renamed:Their Finest Hour- The Battle of Britain (1989)(Lucasfilm Games LLC) [kfx][720k][!].zip-->Their Finest Hour- The Battle of Britain v1.0 (1989)(Lucasfilm Games LLC) [kfx][720k][!].zip
Renamed:Their Finest Hour- The Battle of Britain (1989)(Lucasfilm Games LLC) [IMA][720k][!].zip-->Their Finest Hour- The Battle of Britain v1.0 (1989)(Lucasfilm Games LLC) [IMA][720k][!].zip
Replaced:Their Finest Hour- The Battle of Britain (1989)(Lucasfilm Games LLC) [Action, Simulation].zip-->Their Finest Hour- The Battle of Britain v1.0 (1989)(Lucasfilm Games LLC) [Action, Simulation][!].zip
`

All four listed above are now in the junk pile, replaced by a single replacement pulled from known good disks and cracked with crock2.

**Comment by TotalDOSCollection** [comment]
but wait!  there's more!
Added v1.1 and the Kixx release, which clarified one of the previous [aX] variants we had in TDC before.  It has a unique build of bob.exe and now we have a source for it.

```
Deleted:Their Finest Hour- The Battle of Britain [a3] (1989)(Lucasfilm Games LLC) [Action, Simulation].zip-->dif crack, not needed
Deleted:Their Finest Hour- The Battle of Britain [a2] (1989)(Lucasfilm Games LLC) [Action, Simulation].zip-->dif crack, not needed
Added:Their Finest Hour- The Battle of Britain v1.1 (1990)(Lucasfilm Games LLC) [IMA][720k].zip
Added:Their Finest Hour- The Battle of Britain v1.0 (1989)(Lucasfilm Games LLC) [IMA][360k].zip
Deleted:Their Finest Hour- The Battle of Britain [a1] (1989)(Lucasfilm Games LLC) [Action, Simulation].zip-->Useless after adding [!] in.
Added:Their Finest Hour- The Battle of Britain v1.1 (1989)(Lucasfilm Games LLC) [IMA][360k].zip
Renamed:Their Finest Hour- The Battle of Britain v1.1 (1989)(Lucasfilm Games LLC) [IMA][360k].zip-->Their Finest Hour- The Battle of Britain v1.1 (1990)(Lucasfilm Games LLC) [IMA][360k].zip
Replaced:Their Finest Hour- The Battle of Britain v1.1 (1993)(Lucasfilm Games LLC) [Action, Simulation].zip-->Their Finest Hour- The Battle of Britain v1.1 (1990)(Lucasfilm Games LLC) [Action, Simulation].zip
Added:Their Finest Hour- Battle Of Britain v1.1 (1994)(U.S. Gold Ltd., Kixx, Lucasfilm Games LLC) [IMA][1440k].zip
Replaced:Their Finest Hour- The Battle of Britain [a2] (1989)(Lucasfilm Games LLC) [Action, Simulation].zip-->Their Finest Hour- Battle of Britain v1.1 (1994)(U.S. Gold Ltd., Kixx, Lucasfilm Games LLC) [Action, Simulation].zip

```
sure wish I understood why sometimes my code sections sometimes respect cr/lf and sometimes they don't.
