### ISSUE TITLE
Armor Alley

### ISSUE THREAD

**Issue by bmanbdaman** [TotalDOSCollection/TDCbugs#20]
v1.1 910613 (TDC/rebuilt)
 - 2x 525DD - TGOD#2448
 -- SN: 5JDDDDA
 -- D1 has PSA 1.04 MBR, D2 used to be a Mouseware disk so is suspect
 -- also A-ALLEY[1,2] THG scene release
 -- AA.EXE
 --- 0xE376 558BEC81EC0401 -> B87681BAF679CB
 - Armor Alley v1.1 (1991)(Three-Sixty Pacific, Inc.) [Action, Strategy]
 -- missing AA.EX_
 -- configs PREFS.RES, SOUND.RES
 - rebuilt ; add TGOD IMA as best available

v1.1 920807 (TDC/updated)
 - 2x525DD - TDC
 -- SN: DA2BHWC ; BXAERX2
 -- Armor Alley v1.1 (1992)(Three-Sixty Pacific, Inc.) [IMA][360k][!]
 -- Armor Alley v1.1 (1992)(Three-Sixty Pacific, Inc.) [kfx][360k][!]
 - Armor Alley v1.1 (1992)(Three-Sixty Pacific, Inc.) [Action, Strategy]
 - added 910613 patch
 - updated

v1.1 921113 (new)
 - 1x35DD - TGOD#1877
 - added 910613 patch

old SN list found

EXC2H3Y    EXC53RH    EXC5F33    EXCA992    EXCE8AT    EXCEDJM    EXCJMBF
EXCLBL6    EXCMTCN    EXCNCEP    EXCQRF5    EXCRR6X    EXCSDLL    EXCY2PP
EXD3XPA    EXD89FT    EXDB85R    EXDFPA5    EXDGPPG    EXDH8NL    EXDLAB2
EXDMWHM    EXDREBM    EXDS2QL    EXDTCHB    EXDTY9M    EXDYGQX    EXE3NMF
EXE669P    EXE9583    EXE9QQ3    EXEALLY    EXEDA9C    EXEEXRF    EXEFRMC
EXEHR25    EXEMPJL    EXEQR3E    EXESPMC    EXESXH2    EXEW6T5    EXEXSS3
EXF26LF    EXF3NWH    EXF58G6    EXF5HF6    EXFCBTG    EXFCJXJ    EXFFBFB
EXFFEHW    EXFLMYX    EXFNQ82    EXFR2NC    EXFSNBN    EXFWLQX    EXFWRHR
EXFX6NQ    EXG2A96    EXG563R    EXG8YW2    EXG9G9F    EXG9T2H    EXGBDS5
C9X53TA    C9X53TB    C9X53TC    C9X53T...
A3A56T3    A3A56T5    A3A56T8    A3A56D8

**Comment by TotalDOSCollection** [comment]
`Added:Armor Alley v1.1 (1991)(Three-Sixty Pacific, Inc.) [IMA][360k].zip
Added:Armor Alley v1.1 r921113 (1992)(Three-Sixty Pacific, Inc.) [IMA][720k].zip
Added:Armor Alley v1.1 r921113 (1992)(Three-Sixty Pacific, Inc.) [Action, Strategy].zip
Renamed:Armor Alley v1.1 (1992)(Three-Sixty Pacific, Inc.) [kfx][360k][!].zip-->Armor Alley v1.1 r920807 (1992)(Three-Sixty Pacific, Inc.) [kfx][360k][!].zip
Renamed:Armor Alley v1.1 (1992)(Three-Sixty Pacific, Inc.) [IMA][360k][!].zip-->Armor Alley v1.1 r920807 (1992)(Three-Sixty Pacific, Inc.) [IMA][360k][!].zip
Renamed:Armor Alley v1.1 (1992)(Three-Sixty Pacific, Inc.) [Action, Strategy].zip-->Armor Alley v1.1 r920807 (1992)(Three-Sixty Pacific, Inc.) [Action, Strategy][!].zip
`
I think that does it.  Added wiki notes with serial#s and crack notes.
