### ISSUE TITLE
Scoop, The (1989)

### ISSUE THREAD

**Issue by bmanbdaman** [TotalDOSCollection/TDCbugs#21]
- 1x35DD - TDC/arj0n
 -- /arj0n/Games (IMA,ISO,BIN-CUE)/Scoop, The (1989)(Spinnaker Software Corporation) [Adventure][IMA].zip
 -- Scoop, The (1989)(Spinnaker Software Corporation) [kfx][720k][!]
 -- Scoop, The (1989)(Spinnaker Software Corporation) [IMA][720k][!]
 -- Toshiba MBR "T V2.11 "
 - 2x525DD - TGOD#0344
 -- identical content, includes two label files (011989 21S1, 011989 22S1)
 -- IBMDOS MBR "IBM  3.3"
 - Scoop, The (1989)(Spinnaker Software Corporation) [Adventure].zip
 -- extranneous play files (1995)
 -- missing SCOOP.EX_
 --- SCOOP.EXE 79,251 01-19-1989
 ---- 0x0761 74 -> EB
 -- updated

**Comment by TotalDOSCollection** [comment]
`Replaced:Scoop, The (1989)(Spinnaker Software Corporation) [Adventure].zip-->Scoop, The (1989)(Spinnaker Software Corporation) [Adventure][!].zip
Added:Scoop, The (1989)(Spinnaker Software Corporation) [IMA][360k].zip
`
why do code tags not support my CR/LF combos?

Done.  haven't pulled from arj0n's folder yet, but I bet I have a couple more copies to expunge too.
The [!] 720k has a dozen deleted files, which look like they're from Major League Manager, although they are all garbage.
