### ISSUE TITLE
Battle Isle - Moon of Chromos

### ISSUE THREAD

**Issue by bmanbdaman** [TotalDOSCollection/TDCbugs#22]
Battle Isle '93 - The Moon of Chromos

base (TDC/update)
 - 1x35HD - TDC
 -- /to be sorted/Battle Isle 93.zip [1.44 IMZ].zip
 - Battle Isle '93 - The Moon of Chromos (1993)(Blue Byte Software GmbH) [Strategy]
 -- identical to THG scene release (BI93FIX to address BATISL93 zip problem)
 -- just missing label file (MOND) and wrong folder timestamps
 - MOON.EXE 217,720 05-10-1993
 - NOTE:
 -- titlescreen shows 93, not '93 so is a conundrum
 -- this is also a Slash release according to Moby covers
 - updated

a1 (TDC/delete)
 - Battle Isle '93 - The Moon of Chromos [a1] (1993)(Blue Byte SoftwareGmbH) [Strategy]
 -- the titelescreen shows this without 93 and date is the same as the CD timestamps so this is from a DE CD version
 --- evident because INSTALL from floppy is absent and rename matches (MOON.EXE -> MOON.EX2)
 --- PC Player 08/1997 - Battle Team I (\BONUS\BATTLE\DATA2)
 --- Platinum DE (\BI1D2)
 - delete since part of the compilations and replaced below

Battle Isle Data Disk II - Der Mond von Cromos

base (new)
 - 1x35HD - TGOD#0529
 -- MOND.EX2 216,528 03-31-1993
 - BOX and Manuals are in DE, but this is almost identical to base
 - added

CDs

1994
 - Battle Isle: Data Disk 2 on Battle Isle 2: Scenery CD - Das Erbe des Titan (Limitierte Auflage) - Limited Edition 
 -- this is a possibility according to OGDB

1994
 - Battle Team I
 - not found

1997-06-11
 - redump#083039 - EU - 692,031,312 11e75d8a - PC Player plus CD-ROM 08/97 - Battle Team I - Battle Isle: Data Disk II - Der Mond von Cromos
 -- MC:: SONOPRESS ROM S-9944 A	IFPI L022	IFPI 0731
 -- PVD: PCPL0897   Henrik Fisch   1997061114334500
 -- DEMOS (DOS): Jurassic Primitive War, Shadow Warrior, Waterworld, 
 -- DEMOS (WIN): Betrayal at Antera, Esoteria, Outpost 2, Teracide, Warlords III, Wipout 2097, Yoda
 - cannot find Battle Team I standalone (1994)
 - not adding as this is a Magazine compilation but we could strip out BONUS folder as Battle Team I for now

2000-07-07 (TDC)
 - redump#100491 - DE - 821,986,368 774fdea3 - Battle Isle Platinum D1
 -- Battle Isle: Data Disk 2 - Der Mond von Cromos (\BI1D2)
 -- MC:: Sono press ROMM A-25411/BIPLAT/CD1 A	IFPI LB 45	IFPI 0788
 -- PVD: BI_1___2   CeQuadrat 32bit ISO-9660 Formatter Copyright (c) 1995 by CeQuadrat GmbH   2000070715145331
 - Battle Isle- Platinum (Installer) (De) (2000)(Blue Byte Software GmbH & Co. KG) [Strategy, Compilation]

2000-08-01 (TDC)
 - redump#079520 - EU - 828,480,240 b9c16644 - Battle Isle Platinum D1
 -- Battle Isle '93 - The Moon of Cromos
 -- MC:: Sono press ROMM A-25461/1BIPLAT/GB A	IFPI LB 45	IFPI 0756
 -- PVD: BI1_2   CeQuadrat 32bit ISO-9660 Formatter Copyright (c) 1995 by CeQuadrat GmbH   2000080123551548
 - minor language difference for some of these versions
 - Battle Isle- Platinum (Installer) (2000)(Blue Byte Software GmbH & Co. KG) [Strategy, Compilation]

**Comment by TotalDOSCollection** [comment]
I wonder if that De 1.44mb floppy should really be called "Battle Isle Data Disk No. 2: Der Mond von Chromos"
it's likely this disk:
https://www.mobygames.com/game/6755/battle-isle-93-the-moon-of-chromos/cover/group-19203/cover-132886/

edit: Oh, it looks like that's what you were suggesting. 
```
Renamed:Battle Isle Data Disk II- The Moon of Chromos (1993)(Blue Byte Software GmbH) [IMA][1440k].zip-->Battle Isle Data Disk II- Der Mond von Cromos (1993)(Blue Byte Software GmbH) [IMA][1440k].zip
Renamed:Battle Isle Data Disk II- The Moon of Chromos (1993)(Blue Byte Software GmbH) [Strategy, Addon].zip-->Battle Isle Data Disk II- Der Mond von Cromos (1993)(Blue Byte Software GmbH) [Strategy, Addon].zip

```

whoa, my cr/lf's worked that time.

**Comment by TotalDOSCollection** [comment]
just started putting the BI platinum versions in and then realized they are already in.  heh.  
I think then that this one is finished.

`Deleted:Battle Isle '93 - The Moon of Chromos [a1] (1993)(Blue Byte Software GmbH) [Strategy].zip-->From compilation, not needed standalone
Added:Battle Isle '93- The Moon of Chromos (1993)(Blue Byte Software GmbH, Slash Corporation) [IMA][1440k].zip
Replaced:Battle Isle '93 - The Moon of Chromos (1993)(Blue Byte Software GmbH) [Strategy].zip-->Battle Isle '93- The Moon of Chromos (1993)(Blue Byte Software GmbH, Slash Corporation) [Strategy, Addon].zip
Added:Battle Isle Data Disk II- The Moon of Chromos (1993)(Blue Byte Software GmbH) [IMA][1440k].zip
Added:Battle Isle Data Disk II- The Moon of Chromos (1993)(Blue Byte Software GmbH) [Strategy, Addon].zip
`
