### ISSUE TITLE
Ambush at Sorinor

### ISSUE THREAD

**Issue by bmanbdaman** [TotalDOSCollection/TDCbugs#23]
installer (TDC/new)
 - 2x35HD, 1x35DD - TGOD#2629/TDC ; TGOD#1869
 -- Ambush at Sorinor v1.01 (1993)(Mindcraft Software, Inc.) [IMA][1440k-720k][!]
 -- Ambush at Sorinor v1.01 (1993)(Mindcraft Software, Inc.) [kfx][1440k-720k][!]
 --- odd MBR of "\x00MMI\x003.3"
 -- TGOD#1869 is content identical
 --- empty sectors at end are x00 instead of xF6
 --- found identical as IT distro "Fantasy Ambush" - https://archive.org/details/SFAMAS
 - adding ; decide on !
 -- Ambush at Sorinor v1.01 (Installer) (1993)(Mindcraft Software, Inc.) [Strategy]

base (TDC/rebuilt)
 - Ambush at Sorinor v1.01 (1993)(Mindcraft Software, Inc.) [Strategy]
 -- extranneous files not present from normal install because from RAZOR distro (AMBUSH-[1-3])
 --- DISK1,DISK2,DISK3,GAME.INF, INSTALL.EXE, LASTDISK, SOUNDRV.DPK
 --- seems DB copies label files from D2 and D3, where a standard install does not
 - repacked

v1.02 (TDC/delete)
 - Ambush at Sorinor v1.02 (1993)(Mindcraft Software, Inc.) [Strategy].zip
 -- this is just the patch files dropped in
 - delete

v1.02 Patch (new)
 - Patches Scrolls/archive.org
 - added

ZH (TDC)
 - Ambush at Sorinor (Zh) (1993)(Mindcraft Software, Inc.) [Strategy]
 -- probably from CGM scene release C-AMBUS[1-4]
 -- this said it had a crack (C-AMBUSC)
 - not found

DEMO installer (new)
 - PC Games Coverdisk 09/93
 -- https://archive.org/download/pc-games-92-XX/1993/PC%20Games%201993-09.img
 -- TGOD#3258
 - added

CDs

1994
 - Ambush at Sorinor (CD-ROM) (1993)(Mindcraft Software, Inc.) [Strategy]
 -- CD not found
 - rename v1.01 1994

1995-01-29
 - redump#13788 - DE - 400,877,232 6d245b92 - PC Games CDROM 3/95
 -- MC:: 50203 *   SENTINEL GC 008   *2
 -- PVD:
 -- includes: Ambush at Sorinor ; Siege: Dogs of War ; Bloodstone ; Tegel's Mercenaries
 - \ORIGINAL\AMBUSH
 -- same as 1993 version with DE manual and config

1996-03-04
 - redump#44028 - EU - 20,391,840 f0b15c44 - Ambush at Sorinor
 -- MC:: PROSOFT LOGISTICS 0155-01DIL AMBUSH	IFPI L041
 -- PVD: Ambush   1996030413383900
 - content identical to base CD but has Acrobat and EN PDF manual

**Comment by TotalDOSCollection** [comment]
```
Added:Ambush at Sorinor v1.01 (1996)(Action Sixteen, Mindcraft Software, Inc.) [bin-cue].zip
Renamed:Ambush at Sorinor (CD-ROM) (1993)(Mindcraft Software, Inc.) [Strategy].zip-->Ambush at Sorinor v1.01 (1996)(Action Sixteen, Mindcraft Software, Inc.) [Strategy].zip
Added:Ambush at Sorinor v1.01 (Installer) (1993)(Mindcraft Software, Inc.) [Strategy].zip
Added:Ambush at Sorinor v1.01 (Installer) (1993)(Mindcraft Software, Inc.) [Strategy][!].zip
Added:Ambush at Sorinor (demo) (Installer) (1993)(Mindcraft Software, Inc.) [Strategy].zip
Renamed:Ambush at Sorinor v1.02 (1993)(Mindcraft Software, Inc.) [Strategy].zip-->Ambush at Sorinor 1.02 patch (1993)(Mindcraft Software, Inc.) [Strategy, Addon].zip
Added:PC Games Covermount 09-93 (De) (1993)(Computec Verlag GmbH & Co. KG) [IMA][720k].zip

```

> Ambush at Sorinor (CD-ROM) (1993)(Mindcraft Software, Inc.) [Strategy]
> -- CD not found

This appears to have come from World Combat (1996)(General Admission Software) [Strategy, Compilation].zip so it'll go bye bye.


Not sure what to do with the tgod disk images that are a match, but not really a match.  Possibly a different distribution or manufacturing run.  It may make sense to just wait til kfx images come in.

Thinking outloud, I would like to add covermounts and demos into their own separate folders in the archive for easier sorting.  Will add a database field for them as well (IIRC there's already a database field for demos)
