### ISSUE TITLE
Where in the World is Carmen Sandiego?

### ISSUE THREAD

**Issue by Eulisker** [TotalDOSCollection/TDCbugs#24]
Currently all the "Where in the World is Carmen Sandiego?" games have the same majorID in the database. I would argue there are 3 distinct versions that all should have a different majorID.

The original 1986 release:
![Screenshot 2024-08-01 092506](https://github.com/user-attachments/assets/a0a3d1a2-56e8-46c2-8245-0cba10e95781)

The 1989 Enhanced Edition:
![Screenshot 2024-08-01 092644](https://github.com/user-attachments/assets/28a14798-f44a-488a-acd3-fcb1c0068c66)

The 1990 Deluxe Edition:
![Screenshot 2024-08-01 092836](https://github.com/user-attachments/assets/808b771c-e367-4aac-9beb-aee99447ff69)

These releases belong together:
```
Where in the World is Carmen Sandiego_ v1.0 (1986)(Brøderbund Software, Inc.) [Adventure, Educational].zip
Where in the World is Carmen Sandiego_ v1.0 (1986)(Brøderbund Software, Inc.) [kfx][360k][cp].zip
Where in the World is Carmen Sandiego_ v1.2 (1986)(Brøderbund Software, Inc.) [Adventure, Educational][!].zip
Where in the World is Carmen Sandiego_ v1.2 (1986)(Brøderbund Software, Inc.) [kfx][360k][cp].zip

```
This is the original 1986 version. There is nothing else to be done.

Here comes the 1989 Enhanced version:
```
Where in the World is Carmen Sandiego_ v2.0 (1989)(Brøderbund Software, Inc.) [Adventure, Educational].zip
Where in the World is Carmen Sandiego_ v2.0 (1989)(Brøderbund Software, Inc.) [kfx][360k][cp].zip
Where in the World is Carmen Sandiego_ Enhanced v2.1 (1990)(Brøderbund Software, Inc.) [Adventure, Educational].zip
Where in the World is Carmen Sandiego_ Enhanced v2.1 [a1] (1990)(Brøderbund Software, Inc.) [Adventure, Educational].zip
Where in the World is Carmen Sandiego_ Enhanced v2.2 (1991)(Brøderbund Software, Inc.) [Adventure, Educational].zip
Where in the World is Carmen Sandiego_ Enhanced v2.3 (1992)(Brøderbund Software, Inc.) [Adventure, Educational].zip
Where in the World is Carmen Sandiego_ Enhanced v2.3 (1992)(Brøderbund Software, Inc.) [IMA][720k][!].zip
Where in the World is Carmen Sandiego_ Enhanced v2.3 (1992)(Brøderbund Software, Inc.) [kfx][720k][!].zip
Where in the World is Carmen Sandiego_ (MS-DOS Network) v1.1 (Pt) (1992)(Brøderbund Software, Inc.) [Adventure, Educational].zip
```
Version 2.0 should get the Enhanced in the name. The Portuguese version also i think.
Version 2.3 is not cracked yet.

And finally the Deluxe Edition:
```
Where in the World is Carmen Sandiego_ Deluxe Edition v1.02 (1990)(Brøderbund Software, Inc.) [Adventure, Educational].zip
Where in the World is Carmen Sandiego_ Deluxe Edition v1.02 (Installer) (1990)(Brøderbund Software, Inc.) [Adventure, Educational].zip
Where in the World is Carmen Sandiego_ Deluxe Edition v1.02 [a1] (1990)(Brøderbund Software, Inc.) [Adventure, Educational].zip
Where in the World is Carmen Sandiego_ Deluxe Edition v1.1 (1991)(Brøderbund Software, Inc.) [Adventure, Educational].zip
Where in the World is Carmen Sandiego_ Deluxe Edition v1.1 (Installer) (1991)(Brøderbund Software, Inc.) [Adventure, Educational].zip
Where in the World is Carmen Sandiego_ Deluxe Edition v1.1 (Installer) [a1] (1991)(Brøderbund Software, Inc.) [Adventure, Educational].zip
Where in the World is Carmen Sandiego_ Deluxe Edition v1.2 (1992)(Brøderbund Software, Inc.) [Adventure, Educational].zip
Where in the World is Carmen Sandiego_ (CD-ROM Deluxe Edition) (1992)(Brøderbund Software, Inc.) [Educational].zip
Where in the World is Carmen San Diego_ Deluxe v2.0 (Installer) (1994)(Brøderbund Software, Inc.) [Educational].zip
Where in the World is Carmen Sandiego_ v2.0 (1994)(Brøderbund Software, Inc.) [Educational, Adventure].zip
```

The San Diego part should be renamed to Sandiego. Also with version 2.0 they removed the Deluxe Edition part from the Title Screen. Maybe because they did not have another Carmen Sandiego World version in the market at that point? Or they just wanted to confuse people that want to put all this crap into a database 30 years later.
Anyway. The last 2 should be either "Carmen Sandiego Deluxe Edition v2.0" or just "Carmen Sandiego v2.0"

**Comment by TotalDOSCollection** [comment]
eek.  
I re-pulled files from
Where in the World is Carmen Sandiego_ Enhanced v2.3 (1992)(Brøderbund Software, Inc.) [IMA][720k][!].zip
Where in the World is Carmen Sandiego_ Enhanced v2.3 (1992)(Brøderbund Software, Inc.) [kfx][720k][!].zip
and it's actually where in the USA. so there's other issues to fix here too.

...and
Where in the U.S.A. is Carmen Sandiego_ (1987)(Brøderbund Software, Inc.) [Educational].zip
is v1.1. Thought it was perhaps v1.0 and needed to be renamed, now it gets eliminated.  

`Renamed:Where in the World is Carmen Sandiego_ v2.0 (1989)(Brøderbund Software, Inc.) [kfx][360k][cp].zip-->Where in the World is Carmen Sandiego_ Enhanced v2.0 (1989)(Brøderbund Software, Inc.) [kfx][360k][cp].zip
Renamed:Where in the World is Carmen Sandiego_ v2.0 (1989)(Brøderbund Software, Inc.) [Adventure, Educational].zip-->Where in the World is Carmen Sandiego_ Enhanced v2.0 (1989)(Brøderbund Software, Inc.) [Adventure, Educational].zip
`

v2.3 is now cracked.

**Comment by TotalDOSCollection** [comment]
`
Renamed:Where in the World is Carmen Sandiego_ v2.0 (1989)(Brøderbund Software, Inc.) [kfx][360k][cp].zip-->Where in the World is Carmen Sandiego_ Enhanced v2.0 (1989)(Brøderbund Software, Inc.) [kfx][360k][cp].zip
Renamed:Where in the World is Carmen Sandiego_ v2.0 (1989)(Brøderbund Software, Inc.) [Adventure, Educational].zip-->Where in the World is Carmen Sandiego_ Enhanced v2.0 (1989)(Brøderbund Software, Inc.) [Adventure, Educational].zip
Renamed:Where in the World is Carmen Sandiego_ Enhanced v2.3 (1992)(Brøderbund Software, Inc.) [kfx][720k][!].zip-->Where in the U.S.A. is Carmen Sandiego_ Enhanced v2.3 (1992)(Brøderbund Software, Inc.) [kfx][720k][!].zip
Renamed:Where in the World is Carmen Sandiego_ Enhanced v2.3 (1992)(Brøderbund Software, Inc.) [IMA][720k][!].zip-->Where in the U.S.A. is Carmen Sandiego_ Enhanced v2.3 (1992)(Brøderbund Software, Inc.) [IMA][720k][!].zip
Renamed:Where in the U.S.A. is Carmen Sandiego_ Enhanced v2.3 (1992)(Brøderbund Software, Inc.) [Educational].zip-->Where in the U.S.A. is Carmen Sandiego_ Enhanced v2.3 (1992)(Brøderbund Software, Inc.) [Educational][!].zip
Deleted:Where in the U.S.A. is Carmen Sandiego_ (1987)(Brøderbund Software, Inc.) [Educational].zip-->actually v1.1, not needed
Renamed:Where in the World is Carmen Sandiego_ v1.2 (1986)(Brøderbund Software, Inc.) [Adventure, Educational][!].zip-->Where in the World is Carmen Sandiego_ v1.2 (1986)(Brøderbund Software, Inc.) [Adventure, Educational].zip
Renamed:Where in the World is Carmen Sandiego_ Deluxe v2.0 (Installer) (1994)(Brøderbund Software, Inc.) [Educational, Adventure].zip-->Where in the World is Carmen Sandiego_ v2.0 (Installer) (1994)(Brøderbund Software, Inc.) [Educational, Adventure].zip
Renamed:Where in the U.S.A. is Carmen Sandiego_ Deluxe v2.0 (Installer) (1994)(Brøderbund Software, Inc.) [Educational, Adventure].zip-->Where in the USA is Carmen Sandiego_ v2.0 (Installer) (1994)(Brøderbund Software, Inc.) [Educational, Adventure].zip
Renamed:Where in the U.S.A. is Carmen Sandiego_ Deluxe v2.0 (1994)(Brøderbund Software, Inc.) [Educational, Adventure].zip-->Where in the USA is Carmen Sandiego_ v2.0 (1994)(Brøderbund Software, Inc.) [Educational, Adventure].zip
Added:Where in Space is Carmen Sandiego_ v1.1 (1996)(Brøderbund Software, Inc.) [bin-cue].zip
Added:Where in Space is Carmen Sandiego_ v1.1 (Installer) (1996)(Brøderbund Software, Inc.) [Educational, Adventure].zip
Added:Where in Space is Carmen Sandiego_ v1.1 (1996)(Brøderbund Software, Inc.) [Educational, Adventure].zip
`
not quite done here, haven't moved each into an individual majorID yet, just some house maintenance here.

**Comment by TotalDOSCollection** [comment]
ok, I think this is wrapped up.
`Renamed:Where in the World is Carmen Sandiego_ (MS-DOS Network) v1.1 (Pt) (1992)(Brøderbund Software, Inc.) [Adventure, Educational].zip-->Where in the World is Carmen Sandiego_ Enhanced v1.1 (Pt) (1992)(Brøderbund Software, Inc.) [Adventure, Educational].zip
Added:Where in the World is Carmen Sandiego_ Deluxe Edition CD (1992)(Brøderbund Software, Inc.) [bin-cue].zip
Renamed:Where in the World is Carmen Sandiego_ (CD-ROM Deluxe Edition) (1992)(Brøderbund Software, Inc.) [Educational].zip-->Where in the World is Carmen Sandiego_ Deluxe Edition CD (1992)(Brøderbund Software, Inc.) [Adventure, Educational].zip
Renamed:Where in the World is Carmen Sandiego_ Deluxe Edition CD (1992)(Brøderbund Software, Inc.) [bin-cue].zip-->Where in the World is Carmen Sandiego_ Deluxe Edition CD v1.0 (1992)(Brøderbund Software, Inc.) [bin-cue].zip
Renamed:Where in the World is Carmen Sandiego_ Deluxe Edition CD (1992)(Brøderbund Software, Inc.) [Adventure, Educational].zip-->Where in the World is Carmen Sandiego_ Deluxe Edition CD v1.0 (1992)(Brøderbund Software, Inc.) [Adventure, Educational].zip
Added:Where in the World is Carmen Sandiego_ Deluxe Edition CD v1.1 (1992)(Brøderbund Software, Inc.) [bin-cue].zip
Added:Where in the World is Carmen Sandiego_ Deluxe Edition CD v1.1 (1992)(Brøderbund Software, Inc.) [Adventure, Educational].zip
Added:Where in the World is Carmen Sandiego_ Deluxe Edition CD v1.2 (1993)(Brøderbund Software, Inc.) [bin-cue].zip
Added:Where in the World is Carmen Sandiego_ Deluxe Edition CD v1.2 (1993)(Brøderbund Software, Inc.) [Adventure, Educational].zip
`
added v1.0 CD, v1.1 and v1.2 deluxe editions.

The whole lot now looks like this:

`
¿Dónde está Carmen Sandiego_ ¡Búscala por todo el mundo! (beta) (Es) (1991)(Brøderbund Software, Inc.) [Adventure, Educational].zip -/- (8009.0)
¿Dónde está Carmen Sandiego_ ¡Búscala por todo el Mundo! (Es) (1991)(Brøderbund Software, Inc.) [Adventure, Educational].zip -/- (8009.1)
¿Dónde está Carmen Sandiego_ ¡Búscala por todo el Mundo! (Es) [h1] (1991)(Brøderbund Software, Inc.) [Adventure, Educational].zip -/- (8009.2)
¿Dónde está Carmen Sandiego_ ¡Búscala por todo el Mundo! (Es) [o1] (1991)(Brøderbund Software, Inc.) [Adventure, Educational].zip -/- (8009.3)
A la poursuite de Carmen Sandiego dans le monde (Fr) (1990)(Brøderbund Software, Inc.) [Adventure, Educational].zip -/- (8009.4)
Where in the World is Carmen Sandiego_ Enhanced v1.1 (Pt) (1992)(Brøderbund Software, Inc.) [Adventure, Educational].zip -/- (8009.11)
Where in the World is Carmen Sandiego_ Enhanced v2.0 (1989)(Brøderbund Software, Inc.) [Adventure, Educational].zip -/- (8009.5)
Where in the World is Carmen Sandiego_ Enhanced v2.0 (1989)(Brøderbund Software, Inc.) [kfx][360k][cp].zip -/- (8009.10)
Where in the World is Carmen Sandiego_ Enhanced v2.1 (1990)(Brøderbund Software, Inc.) [Adventure, Educational].zip -/- (8009.6)
Where in the World is Carmen Sandiego_ Enhanced v2.1 [a1] (1990)(Brøderbund Software, Inc.) [Adventure, Educational].zip -/- (8009.7)
Where in the World is Carmen Sandiego_ Enhanced v2.2 (1991)(Brøderbund Software, Inc.) [Adventure, Educational].zip -/- (8009.8)
Where in the World is Carmen Sandiego_ Enhanced v2.3 (1992)(Brøderbund Software, Inc.) [Adventure, Educational].zip -/- (8009.9)

Where in the World is Carmen Sandiego_ v1.0 (1986)(Brøderbund Software, Inc.) [Adventure, Educational].zip -/- (8389.1)
Where in the World is Carmen Sandiego_ v1.0 (1986)(Brøderbund Software, Inc.) [kfx][360k][cp].zip -/- (8389.0)
Where in the World is Carmen Sandiego_ v1.2 (1986)(Brøderbund Software, Inc.) [Adventure, Educational].zip -/- (8389.3)
Where in the World is Carmen Sandiego_ v1.2 (1986)(Brøderbund Software, Inc.) [kfx][360k][cp].zip -/- (8389.2)


Where in the World is Carmen Sandiego_ Deluxe Edition CD v1.0 (1992)(Brøderbund Software, Inc.) [Adventure, Educational].zip -/- (17628.0)
Where in the World is Carmen Sandiego_ Deluxe Edition CD v1.0 (1992)(Brøderbund Software, Inc.) [bin-cue].zip -/- (17628.10)
Where in the World is Carmen Sandiego_ Deluxe Edition CD v1.1 (1992)(Brøderbund Software, Inc.) [Adventure, Educational].zip -/- (17628.12)
Where in the World is Carmen Sandiego_ Deluxe Edition CD v1.1 (1992)(Brøderbund Software, Inc.) [bin-cue].zip -/- (17628.11)
Where in the World is Carmen Sandiego_ Deluxe Edition CD v1.2 (1993)(Brøderbund Software, Inc.) [Adventure, Educational].zip -/- (17628.14)
Where in the World is Carmen Sandiego_ Deluxe Edition CD v1.2 (1993)(Brøderbund Software, Inc.) [bin-cue].zip -/- (17628.13)
Where in the World is Carmen Sandiego_ Deluxe Edition v1.02 (1990)(Brøderbund Software, Inc.) [Adventure, Educational].zip -/- (17628.2)
Where in the World is Carmen Sandiego_ Deluxe Edition v1.02 (Installer) (1990)(Brøderbund Software, Inc.) [Adventure, Educational].zip -/- (17628.1)
Where in the World is Carmen Sandiego_ Deluxe Edition v1.02 [a1] (1990)(Brøderbund Software, Inc.) [Adventure, Educational].zip -/- (17628.6)
Where in the World is Carmen Sandiego_ Deluxe Edition v1.1 (1991)(Brøderbund Software, Inc.) [Adventure, Educational].zip -/- (17628.5)
Where in the World is Carmen Sandiego_ Deluxe Edition v1.1 (Installer) (1991)(Brøderbund Software, Inc.) [Adventure, Educational].zip -/- (17628.3)
Where in the World is Carmen Sandiego_ Deluxe Edition v1.1 (Installer) [a1] (1991)(Brøderbund Software, Inc.) [Adventure, Educational].zip -/- (17628.4)
Where in the World is Carmen Sandiego_ Deluxe Edition v1.2 (1992)(Brøderbund Software, Inc.) [Adventure, Educational].zip -/- (17628.9)
Where in the World is Carmen Sandiego_ v2.0 (1994)(Brøderbund Software, Inc.) [Educational, Adventure].zip -/- (17628.8)
Where in the World is Carmen Sandiego_ v2.0 (Installer) (1994)(Brøderbund Software, Inc.) [Educational, Adventure].zip -/- (17628.7)

`
(OMG the code tag here so completely broken!)

Each of the 3 has its own major ID now, and I've aligned some of the oddball names to bring them all together.
Feel free to open additional reports as needed if something here wasn't covered, and that's of course just 1 of the Carmen series...
