### ISSUE TITLE
Solitaire's Journey

### ISSUE THREAD

**Issue by bmanbdaman** [TotalDOSCollection/TDCbugs#25]
base installer WIN31
 - 1x35DD - TGOD#2965
 - not added

base installer (TDC/updated)
 - 1x35DD - not found
 - SOLIT.002 is a subsection (0x0-0x6DDCF) of SOLIT.001
 -- duplicate file - game installs fine without the extra copied data
 - Solitaire's Journey v1.00 (Installer) (1992)(Quantum Quality Productions) [Strategy, Cards]
 -- rebuilt - deleted SOLIT.002

base (TDC/updated)
 - Solitaire's Journey v1.00 (1992)(Quantum Quality Productions) [Strategy, Cards]
 - SOLIT.EXE
 -- 0x18BCB 7F -> EB (not clean - doc check any answer)
 - matches installed except someone deleted initial SOUND\SOLMUSIC.CFG
 -- could be rebuilt from SOLSETUP.EXE but exists because install created first run setup
 - timestamps are all point-in-time so re-installed
 - rebuilt

base installer a1 (TDC/updated)
 - 2x525DD - TGOD#1449
 -- interesting MBR - "C ZDS3.3"
 -- they also filled every byte on D1 so that is crazy
 - this requires a disk label after the first disk
 -- my labelfixer did not fix this, only a real disk label worked so maybe DB issue
 - creates identical output to base
 - Solitaire's Journey v1.00 (Installer) [a1] (1992)(Quantum Quality Productions) [Strategy, Cards].zip
 -- missing D2 DISK.ID (probably overwritten) and disk labels
 --- both needed to write back to disk for working install
 - rebuilt ; add IMA

NOTE: are we going to come up with a convention for installers that create identical content? a1 implies a different output

v1.03 installer (TDC)
 - 1x35DD - TDC
 -- Solitaire's Journey v1.03 (1993)(Quantum Quality Productions) [IMA][720k][!]
 - Solitaire's Journey v1.03 (Installer) (1993)(Quantum Quality Productions) [Strategy, Cards][!]
 - matches

v1.03 (TDC/updated)
 - Solitaire's Journey v1.03 (1993)(Quantum Quality Productions) [Strategy, Cards].zip
 - SOLIT.EXE 09-21-1992 (did not need to be expanded)
 -- 0x1D1E9 7F -> EB (old expanded)
 -- 0x18A69 7F -> EB (not clean - doc check any answer)
 - matches installed except someone deleted initial SOUND\SOLMUSIC.CFG
 -- could be rebuilt from SOLSETUP.EXE but exists because install created first run setup
 - timestamps are all point-in-time so re-installed
 - rebuilt

**Comment by TotalDOSCollection** [comment]
done.  
mostly just dropping these new ones over the existing TDC copies, so no real logging was done.
`Added:Solitaire's Journey v1.00 (1992)(Quantum Quality Productions) [IMA][360k].zip
`
Doing my own housecleaning, I have found 2 alternate cracks which all the doc check to be done in 1 attempt instead of 3.  I replaced the cracked exe in the installed copy with one of those and stashed the other alternate cracks in the dustbin for tracking purposes.
