### ISSUE TITLE
Disney's Duck Tales- The Quest for Gold v1.0 (1990)

### ISSUE THREAD

**Issue by bmanbdaman** [TotalDOSCollection/TDCbugs#26]
Both versions are identical except for labels, so there should only be a base and a1.

 - 2x525DD - TGOD#1147/TDC
 -- /floppy_images/to be sorted/Disney's Duck Tales-The Quest For Gold [360k IMZ].zip
 -- /floppy_images/from original disks/Disney's Duck Tales- The Quest for Gold (1990)(Walt Disney Computer Software, Inc.) [td0].zip
 -- Disney's Duck Tales- The Quest for Gold v1.0 (1990)(Walt Disney Computer Software, Inc.) [IMA][360k][!]
 -- Disney's Duck Tales- The Quest for Gold v1.0 (1990)(Walt Disney Computer Software, Inc.) [kfx][360k][!]
 -- labels are "DUCKTALES 1" and "DUCKTALES 2"
 
 - 1x35DD - TDC/arj0n
 -- /arj0n/Games (IMA,ISO,BIN-CUE)/Disney's Duck Tales- The Quest for Gold (1990)(WaltDisney Computer Software, Inc.) [Action][IMA].zip
 -- Disney's Duck Tales- The Quest for Gold v1.0 (1990)(Walt Disney Computer Software, Inc.) [IMA][720k][!]
 -- Disney's Duck Tales- The Quest for Gold v1.0 (1990)(Walt Disney Computer Software, Inc.) [kfx][720k][!]
 -- label is "DUCKTALES"

Patches
 - Neverlock		0BC0 -> 09ED (not clean, accepts any answer)
 - generic cheat list	7503 -> 7500 (clean, shows intro)
 - Crock		7503 -> 7500 (clean, shows intro)
 - THG			7404 -> EB-- (clean, shows intro)

base (TDC/delete)
 - Disney's Duck Tales- The Quest for Gold (1990)(Walt Disney Computer Software, Inc.) [Action]
 -- DUCKTALE.EXE 165,218
 --- 0x1069C 7404 -> EB-- (THG patch)
 --- 0x1090F 0BC0 -> 09ED (Neverlock patch)
 - delete, double patched

a1 (TDC/delete)
 - Disney's Duck Tales- The Quest for Gold [a1] (1990)(Walt Disney Computer Software, Inc.) [Action]
 -- TZIP
 -- missing README files
 -- DUCKTALE.EXE
 --- 0xCA87 Bill Zielinski      .    Art Direction by:    .     Denise Wallner      .
 --- -----> Gerard Jansen       .    Art Direction by:    .     BB Funsoft  90      .
 -- 0x1069C 74 -> EB (THG patch)
 - this is h1 from a NL cracker group so shelve

a2 (TDC/delete)
 - Disney's Duck Tales- The Quest for Gold [a2] (1990)(Walt Disney Computer Software, Inc.) [Action]
 -- missing README files
 -- DUCKTALE.EXE 165,218 1980
 --- 0x1069C 74 -> EB (THG patch)
 - already patched, has a THG banner (.COM, shout out to FF, not a patch loader per se)
 - delete, rebuilt as a1

a3 (TDC/delete)
 - Disney's Duck Tales- The Quest for Gold [a3] (1990)(Walt Disney Computer Software, Inc.) [Action]
 -- includes 525 labels
 -- DUCKTALE.EXE 165,218 2015
 --- 0x10854 7503-> --00 (Crock patch)
 - delete ; updated timestamp and made base

Delete WIKI notes. Update to reflect base as Crock 525DD, a1 as THG 35DD.

**Comment by TotalDOSCollection** [comment]
ok, all duck tales items cleaned up and documented.  skipped the [a1] files set as the only difference is the floppy label.
