### ISSUE TITLE
Baryon (1995)

### ISSUE THREAD

**Issue by bmanbdaman** [TotalDOSCollection/TDCbugs#4]
installer (new)
 - Added from Razor release (BARYON[1-8])
 - moved DISK2-8 file into sub folder or installer repeats 7 more times
 - uploaded

base (TDC)
 - Baryon [SWR] (1995)(The Game Factory) [Action]
 - matches installation from installer

**Comment by TotalDOSCollection** [comment]
`Added:Baryon (Installer) [SWR] (1995)(The Game Factory) [Action].zip
`
* Baryon (Installer) [SWR] (1995)(The Game Factory) [Action].zip - source unknown (razor scene release), appears to be 8x1.44mb floppies.  Each disk has a file DISKx where x is from 1 to 8.  All files are identical with identical timestamps.  When merging all disk files into an archive and then installing off the hard drive, the installer will re-run 8 times if all 8 DISKx files are present, so this archive only has 1.

**Comment by TotalDOSCollection** [comment]
`Added:Baryon [SWR] (1995)(The Game Factory, CDV Software Entertainment AG) [bin-cue].zip
Added:Baryon CD (Installer) (1995)(The Game Factory, CDV Software Entertainment AG) [Action].zip
Added:Baryon CD (1995)(The Game Factory, CDV Software Entertainment AG) [Action].zip
`
* Baryon CD (Installer) (1995)(The Game Factory, CDV Software Entertainment AG) [Action].zip - CD-ZIP of redump's bin-cue http://redump.org/disc/48875/  Installer checks for CD, bypassed by forcing it to just work from current folder.  The CD's main menu is (En) or (De) but the game itself is always En. crack:
<pre>
Comparing files INSTALL.EX_ and INSTALL.EXE
000055EE: 74 EB
</pre>
* Baryon CD (1995)(The Game Factory, CDV Software Entertainment AG) [Action].zip - Different release than floppy version, has long intro animation.  Installer only copies the bare essentials and assumes the CD is available to load extra data.  This version runs from any folder without additional mounted/installed files.  The game attempts to load and run dos4gw.exe from all paths in the path environment but never seems to try it in the local default directory(?!).  Patched to remove changing default drive, which keeps it local and then it finds dos4gw just fine.
<pre>
Comparing files GO.CO_ and GO.COM
000019DF: CD 90
000019E0: 21 90
</pre>
