### ISSUE TITLE
Wild West (DE) (Pro Line) (1994)

### ISSUE THREAD

**Issue by bmanbdaman** [TotalDOSCollection/TDCbugs#5]
That 12/20/93 date on the base is too close to 1994 to think this was rolled out in 1993 so updating after finding a rare pic.
 - https://www.computerbase.de/forum/threads/suche-wild-west-adventure-von-proline.308625/
 - https://www.computerbase.de/forum/attachments/10001343_10201021831067938_6138266157973517587_n-jpg.546287/

base (TDC/updated)
 - Wild West - The Incredible Adventures of Donald Reddish (De) (1993)(PROLINE Software) [Adventure]
 -- matches installed
 -- install normally retains UNARJ.EXE
 - INSTALL.EXE has the installed timestamp (2016)
 -- replaced with original (1993)
 - delete ; updated as 1994

installer (new)
 - 6x35HD - TGOD#2273/Sammler/TDC (tobesorted)
 -- /to be sorted/_erstupload_sammler/Wild West [DE-Sub][Dos][Diskette][Vollversion+Demo].zip
 -- /to be sorted/Wild West - The Incredible Adventures of Donald Reddish (De) (1993)(PROLINE Software) [IMG].zip
 -- all D4 are IMZ so needs extracting

demo (TDC/delete/fixed)
 - Wild West (De) [SW] (1994)(PROLINE Software) [Adventure]
 -- matches extraction of installer data
 -- install normally retains UNARJ.EXE and creates WWDEMO.CFG
 - needs INSTALL.EXE to modify config
 - needs WWDEMO.CFG to actually make it work because it gets created by default
 - delete ; added both into f1

installer demo (new)
 - 1x35HD - TGOD#2274/Sammler/TDC (tobesorted)
 -- /to be sorted/_erstupload_sammler/Wild West [DE-Sub][Dos][Diskette][Vollversion+Demo].zip
 -- /to be sorted/Wild West (De) [SW] (1994)(PROLINE Software) [IMG].zip

**Comment by TotalDOSCollection** [comment]
```
Replaced:Wild West - The Incredible Adventures of Donald Reddish (De) (1993)(PROLINE Software) [Adventure].zip-->Wild West - The Incredible Adventures of Donald Reddish (De) (1994)(PROLINE Software) [Adventure].zip
Added:Wild West - The Incredible Adventures of Donald Reddish (De) (1994)(PROLINE Software) [IMA][1440k].zip
Added:Wild West - The Incredible Adventures of Donald Reddish (Installer) (De) (1994)(PROLINE Software) [Adventure].zip
Added:Wild West (De) [SW] (1994)(PROLINE Software) [IMA][1440k].zip
Added:Wild West (Installer) (De) [SW] (1994)(PROLINE Software) [Adventure].zip
```
