### ISSUE TITLE
Wing Commander II

### ISSUE THREAD

**Issue by bmanbdaman** [TotalDOSCollection/TDCbugs#9]
Lots of things happening here to straighten this out. Game is optionally in-place decompressed (same file names), converted to EGA files, and installer even references needing to re-install either option change. It also has 3 special packs (SO1/SO2/SP) that have to be installed in the correct order.  

```
Wing Commander II- Vengeance of the Kilrathi (Installer) (1991)(ORIGIN Systems, Inc.) [Action, Simulation]
 -> rename v4.0 [!]
Wing Commander II- Vengeance of the Kilrathi v4.0 (Installer) [a1] (1991)(ORIGIN Systems, Inc.) [Action, Simulation]
 -> added
Wing Commander II- Vengeance of the Kilrathi v4.0 (1991)(ORIGIN Systems, Inc.) [IMA][720k]
 -> added
Wing Commander II- Vengeance of the Kilrathi v4.0 (Installer) [a2] (1991)(ORIGIN Systems, Inc.) [Action, Simulation]
 -> added
Wing Commander II- Vengeance of the Kilrathi v4.0 (1991)(ORIGIN Systems, Inc.) [Action, Simulation]
 -> delete / b1
Wing Commander II- Vengeance of the Kilrathi (De) (1992)(ORIGIN Systems, Inc.) [IMA][1200k]
 -> added
Wing Commander II- Vengeance of the Kilrathi (Installer) (De) (1992)(ORIGIN Systems, Inc.) [Action, Simulation]
 -> added
Wing Commander II- Vengeance of the Kilrathi (De) (1992)(ORIGIN Systems, Inc.) [IMA][1440k]
 -> added
Wing Commander II- Vengeance of the Kilrathi (Installer) (De) [a1] (1992)(ORIGIN Systems, Inc.) [Action, Simulation]
 -> added
Wing Commander II- Vengeance of the Kilrathi - Special Operations 1 (1991)(ORIGIN Systems, Inc.) [Addon]
 -> rename (Installer) [Simulation, Addon][!]
Wing Commander II- Vengeance of the Kilrathi - Special Operations 1 (1991)(ORIGIN Systems, Inc.) [IMA][720k]
 -> added
Wing Commander II- Vengeance of the Kilrathi - Special Operations 1 (Installer) [a1] (1991)(ORIGIN Systems, Inc.) [Simulation, Addon]
 -> added
Wing Commander II- Vengeance of the Kilrathi - Special Operations 1 (1991)(ORIGIN Systems, Inc.) [IMA][1200k]
 -> added
Wing Commander II- Vengeance of the Kilrathi - Special Operations 1 (Installer) [a2] (1991)(ORIGIN Systems, Inc.) [Simulation, Addon]
 -> added
Wing Commander II- Vengeance of the Kilrathi - Special Operations 1 (Fr) (1992)(ORIGIN Systems, Inc.) [IMA][1440k]
 -> added
Wing Commander II- Vengeance of the Kilrathi - Special Operations 1 (Installer) (Fr) (1992)(ORIGIN Systems, Inc.) [Simulation, Addon]
 -> added
Wing Commander II- Vengeance of the Kilrathi - Special Operations 2 (Installer) (1992)(ORIGIN Systems, Inc.) [Simulation, Addon][!]
 -> added
Wing Commander II- Vengeance of the Kilrathi - Special Operations 2 (1992)(ORIGIN Systems, Inc.) [Simulation, Addon][!]
 -> rename (Installer) [a1] ; remove [!]
Wing Commander II- Vengeance of the Kilrathi - Speech Accessory Pack (Installer) (1991)(ORIGIN Systems, Inc.) [Simulation, Addon][!]
 -> added
Wing Commander II- Vengeance of the Kilrathi - Speech Accessory Pack (1991)(ORIGIN Systems, Inc.) [IMA][1200k]
 -> added
Wing Commander II- Vengeance of the Kilrathi - Speech Accessory Pack (Installer) [a1] (1991)(ORIGIN Systems, Inc.) [Simulation, Addon]
 -> added
Wing Commander II- Vengeance of the Kilrathi - Speech Accessory Pack(1991)(ORIGIN Systems, Inc.) [Addon]
 -> rename (Installer) [a2] [Simulation, Addon]
Wing Commander II- Deluxe Edition (1992)(ORIGIN Systems, Inc.) [Action, Simulation]
 -> added
Wing Commander - Wing Commander II (Special CD-ROM Edition (1994)(ORIGIN Systems, Inc.) [Compilation]
 -> added
Ultima Underworld- The Stygian Abyss - Wing Commander II- Vengeance of the Kilrathi (CD-ROM Edition) (1992)(ORIGIN Systems, Inc.) [Compilation][!]
 -> maybe re-zip to fix folder timestamps
```

base v4.0 installer (TDC/rename)
 - 8x525HD - TGOD#0750/TDC
 -- Wing Commander II- Vengeance of the Kilrathi v4.0 (1991)(ORIGIN Systems, Inc.) [kfx][1200k][!]
 -- Wing Commander II- Vengeance of the Kilrathi v4.0 (1991)(ORIGIN Systems, Inc.) [IMA][1200k][!]
 - Wing Commander II- Vengeance of the Kilrathi (Installer) (1991)(ORIGIN Systems, Inc.) [Action, Simulation]
 -- matches ; missing labels
 - rename v4.0 [!]

base v4.0 installer a1 (TDC/new)
 - 7x35HD - TGOD#1639/TDC ; TGOD#1719
 -- Wing Commander II- Vengeance of the Kilrathi v4.0 (1991)(ORIGIN Systems, Inc.) [IMA][1440k][!]
 -- Wing Commander II- Vengeance of the Kilrathi v4.0 (1991)(ORIGIN Systems, Inc.) [kfx][1440k][!]
 -- TGOD#1719 different D7 (12 empty blocks show xF6 instead of random data for 1639 - odd but no files impacted)
 - different INSTALL.DAT
 - adding
 -- Wing Commander II- Vengeance of the Kilrathi v4.0 (Installer) [a1] (1991)(ORIGIN Systems, Inc.) [Action, Simulation]

base v4.0 installer a2 (new)
 - 14x35DD - random torrent find (2018)
 - different INSTALL.DAT
 - adding
 -- Wing Commander II- Vengeance of the Kilrathi v4.0 (1991)(ORIGIN Systems, Inc.) [IMA][720k]
 -- Wing Commander II- Vengeance of the Kilrathi v4.0 (Installer) [a2] (1991)(ORIGIN Systems, Inc.) [Action, Simulation]

base v4.0 (TDC/delete)
 - Wing Commander II- Vengeance of the Kilrathi v4.0 (1991)(ORIGIN Systems, Inc.) [Action, Simulation]
 -- this munges	WCI Secret Missions 2 installer in the game folder
 - delete ; too many variations between base+EGA/VGA+SO1+SO2+SP+compressed/uncompressed+soundoptions ; there are CD editions

base installer DE (new)
 - 8x525HD - TGOD#0108
 - adding
 -- Wing Commander II- Vengeance of the Kilrathi (De) (1992)(ORIGIN Systems, Inc.) [IMA][1200k]
 -- Wing Commander II- Vengeance of the Kilrathi (Installer) (De) (1992)(ORIGIN Systems, Inc.) [Action, Simulation]

base installer DE a1 (new)
 - 7x35HD - gruby
 - different INSTALL.DAT, INSTALL.EXE, MODULE.000, WC2.LZC
 - adding
 -- Wing Commander II- Vengeance of the Kilrathi (De) (1992)(ORIGIN Systems, Inc.) [IMA][1440k]
 -- Wing Commander II- Vengeance of the Kilrathi (Installer) (De) [a1] (1992)(ORIGIN Systems, Inc.) [Action, Simulation]

Special Operations 1 (really installer) (TDC/rename)
 - 2x35HD - TGOD#3285/1226/TDC
 -- Wing Commander II- Vengeance of the Kilrathi - Special Operations 1 (1991)(ORIGIN Systems, Inc.) [kfx][1440k][!]
 -- Wing Commander II- Vengeance of the Kilrathi - Special Operations 1 (1991)(ORIGIN Systems, Inc.) [IMA][1440k][!]
 -- TGOD#1226 is truncated (missing extra xF6s)
 - Wing Commander II- Vengeance of the Kilrathi - Special Operations 1 (1991)(ORIGIN Systems, Inc.) [Addon]
 -- matches ; only missing labels
 -- rename: (Installer) [Simulation, Addon][!]
 
Special Operations 1 installer a1 (new)
 - 4x35DD - TGOD#0920
 -- different installer references due to disk sizes
 - adding
 -- Wing Commander II- Vengeance of the Kilrathi - Special Operations 1 (1991)(ORIGIN Systems, Inc.) [IMA][720k]
 -- Wing Commander II- Vengeance of the Kilrathi - Special Operations 1 (Installer) [a1] (1991)(ORIGIN Systems, Inc.) [Simulation, Addon]

Special Operations 1 installer a2 (new)
 - 2x525HD - gruby
 -- different installer references due to disk sizes
 - adding
 -- Wing Commander II- Vengeance of the Kilrathi - Special Operations 1 (1991)(ORIGIN Systems, Inc.) [IMA][1200k]
 -- Wing Commander II- Vengeance of the Kilrathi - Special Operations 1 (Installer) [a2] (1991)(ORIGIN Systems, Inc.) [Simulation, Addon]

Special Operations 1 installer FR (new)
 - 2x35HD - TGOD#0414
 - adding
 -- Wing Commander II- Vengeance of the Kilrathi - Special Operations 1 (Fr) (1992)(ORIGIN Systems, Inc.) [IMA][1440k]
 -- Wing Commander II- Vengeance of the Kilrathi - Special Operations 1 (Installer) (Fr) (1992)(ORIGIN Systems, Inc.) [Simulation, Addon]

Special Operations 2 installer (TDC/new)
 - 2x35HD - TGOD#0921/TDC
 -- Wing Commander II- Vengeance of the Kilrathi - Special Operations 2 (1992)(ORIGIN Systems, Inc.) [IMA][1440k][!]
 -- Wing Commander II- Vengeance of the Kilrathi - Special Operations 2 (1992)(ORIGIN Systems, Inc.) [kfx][1440k][!]
 - adding
 -- Wing Commander II- Vengeance of the Kilrathi - Special Operations 2 (Installer) (1992)(ORIGIN Systems, Inc.) [Simulation, Addon][!]

Special Operations 2 (really installer a1) (TDC/rename)
 - 4x35DD - not found
 - Wing Commander II- Vengeance of the Kilrathi - Special Operations 2 (1992)(ORIGIN Systems, Inc.) [Simulation, Addon][!]
 - not matching 2x35HD because installer differences - INSTALL2.EXE, INSTALL2.DAT, SERIES.S02, SO2.LZC
 - rename (Installer) [a1] ; remove ! ; missing labels

These all produce the same output when installed. Each installer has ONE unique DAT file that breaks out the merge content

Speech Accessory Pack installer (TDC/new)
 - 3x35HD - TGOD#1815/TDC ; TGOD#0415
 -- Wing Commander II- Vengeance of the Kilrathi - Speech Accessory Pack (1991)(ORIGIN Systems, Inc.) [IMA][1440k][!]
 -- Wing Commander II- Vengeance of the Kilrathi - Speech Accessory Pack (1991)(ORIGIN Systems, Inc.) [kfx][1440k][!]
 -- TGOD#0415 - access times, MBR Win munge ; SPEECH._XE file
 - adding
 -- Wing Commander II- Vengeance of the Kilrathi - Speech Accessory Pack (Installer) (1991)(ORIGIN Systems, Inc.) [Simulation, Addon][!]

Speech Accessory Pack installer a1 (new)
 - 3x525HD - TGOD#1225 ; TGOD#0751
 -- TGOD#1225 D2 has bad blocks (COMMUNIC.S14, COMMUNIC.S24, SPEECH.S02)
 - SPEECH.DAT
 -- same content ; re-arranged structure (disk locations)
 - adding
 -- Wing Commander II- Vengeance of the Kilrathi - Speech Accessory Pack (1991)(ORIGIN Systems, Inc.) [IMA][1200k]
 -- Wing Commander II- Vengeance of the Kilrathi - Speech Accessory Pack (Installer) [a1] (1991)(ORIGIN Systems, Inc.) [Simulation, Addon]

Speech Accessory Pack installer a2 (TDC/rename)
 - unkn media size - not found
 - Wing Commander II- Vengeance of the Kilrathi - Speech Accessory Pack(1991)(ORIGIN Systems, Inc.) [Addon]
 - SPEECH.DAT
 -- same content ; re-arranged structure (disk locations)
 - rename (Installer) [a2] [Simulation, Addon]

CDs
 

1992-07-10 (TDC)
 - redump#106088 - US - 47,174,064 85ee2fb0 - Ultima Underworld: The Stygian Abyss / Wing Commander II: Vengeance of the Kilrathi
 -- Ultima Underworld- The Stygian Abyss - Wing Commander II- Vengeance of the Kilrathi (CD-ROM Edition) (1992)(ORIGIN Systems, Inc.) [bin-cue][!]
 -- MC:: W.O. 53140-1M   53140   DISC MFG, INC. (H)
 -- PVD: WING_CD2   WING_CD2   ORIGIN   NIMBUS   1992071015170000
 -- WING2 folder includes base+VGA/EGA+SpeechPack already installed
 - Ultima Underworld- The Stygian Abyss - Wing Commander II- Vengeance of the Kilrathi (CD-ROM Edition) (1992)(ORIGIN Systems, Inc.) [Compilation][!]
 -- folder timstamps are incorrect

1992-08-18 (new)
 - redump#010372 - US - 32,276,496 0fdccd7b - Wing Commander II: Deluxe Edition
 -- MC:: DISC MFG, INC. (H)   W.O. 53160-1   53160
 -- PVD: WING_CD1   WING_CD1   ORIGIN   NIMBUS   1992081808503100
 -- WING2 folder includes base+VGA+SO1+SO2+SpeechPack already installed
 - adding
 -- Wing Commander II- Deluxe Edition (1992)(ORIGIN Systems, Inc.) [Action, Simulation]

1994-07-19 (new)
 - redump#080031 - US - 38,866,800 77eda177 - Wing Commander / Wing Commander II (Special CD-ROM Edition)
 -- MC:: STARPACK 1009221   51369-01
 -- PVD: Volume Set ID   Tempra CD-Producer,1.2b   Application   1994071909352248
 - WING2 folder identical to Deluxe
 - adding
 -- Wing Commander - Wing Commander II (Special CD-ROM Edition (1994)(ORIGIN Systems, Inc.) [Action, Simulation, Compilation]

1994-07-19 (not found)
 - redump#100338 - EU - 38,518,704 884b2f26 - Wing Commander / Wing Commander II (Twin Pack CD-ROM Edition)
 -- MC:: CDR00228   PC WISE
 -- PVD:

1994-08-29 (not added)
 - redump#002939 - US - 320,683,440 b615c50f - 4 Games in 1: Strike Commander + Syndicate Plus + Ultima VIII: Pagan + Wing Commander II (Bundle Version OEM)
 -- MC:: ???
 -- PVD: KLONEMEISTER CDMELTER   EA1   CREATIVE LABS, INC.   JP   DISCOMPOSER 1.01   1994082912513400
 - WING2 folder identical to Deluxe

1994-08-30 (already added from PGA Tour II)
 - EA Top 10 Pak (Compilation)
 --  Chuck Yeager's Air Combat, Grand Slam Bridge II, Indianapolis 500: The Simulation, Kasparov's Gambit, PGA Tour Golf, SEAL Team, Ultima VII: The Black Gate, Ultrabots, Wing Commander II: Vengeance of the Kilrathi, Financial Workshop
 -- https://archive.org/details/top-ten-pak
 -- PVD: TOP_TEN_PAK   ELECTRONIC ARTS   PDSC IS 2.0IS20773168Electronic Arts MAstering Lab
 - WING2 folder content created by custom installer is identical to base

1995-02-11 (not added)
 - redump#067724 - US - 51,781,632 8e280241 - Wing Commander II: Deluxe Edition (CDROM Classics)
 -- MC:: KAO OPTICAL PRODUCTS ***RF008210-002*** 538607
 -- PVD: Trace (Enlighten CD-ROM Products), disComposer 1.0   disComposer   19950211132120000
 - identical to original Deluxe Edition + Acrobat + Manual

1995-04-28 (new, not added)
 - https://archive.org/details/wing-commander-ii-vengeance-of-the-kilrathi-1992-en-r-8885-cxd-cd-rom-classic.-7z
 -- MC:: 
 -- PVD: WING   CEQUADRAT ISO 9660 FORMATTER SERIAL NUMBER  25724   (C) 1993 BY CEQUADRAT AACHEN GERMANY   1995042815431300
 - this adds new DE/FR/EN manuals but identical to Deluxe

1996-09-24 (not added)
 Win95 - Wing Commander: The Kilrathi Saga

1996 (not found)
 EU - Telstar Double Value Games: Hi-Octane & Wing Commander II

**Comment by TotalDOSCollection** [comment]
I should first really say thank you for tackling this huge job.  this series is one I've been dreading to process since there seemed to be so many variants.  At least we have some disk images to work off instead of just a bunch of scene releases.


> base installer DE a1 (new)
> 
>     7x35HD - gruby
>     different INSTALL.DAT, INSTALL.EXE, MODULE.000, WC2.LZC
>     adding
>     -- Wing Commander II- Vengeance of the Kilrathi (De) (1992)(ORIGIN Systems, Inc.) [IMA][1440k]
>     -- Wing Commander II- Vengeance of the Kilrathi (Installer) (De) [a1] (1992)(ORIGIN Systems, Inc.) [Action, Simulation]

So this says it's version "GE1.5F" when I do a Ctrl-V inside the flying phase.  That matches the volume labels so I'll be adding that in.
Oh and the 1.2mb version is GE1.7F so we don't even need the [a1] since we will have unique filenames off the version itself.  hurray!

> 
> -- Wing Commander II- Vengeance of the Kilrathi - Special Operations 1 (Fr) (1992)(ORIGIN Systems, Inc.) [IMA][1440k]
> -- Wing Commander II- Vengeance of the Kilrathi - Special Operations 1 (Installer) (Fr) (1992)(ORIGIN Systems, Inc.) 

Happen to know if the French SO1 disk needs a French WC2 to install onto?  I am getting a file corrupt error for LANDGAME.V20 during installation, but lacking a french version of the base game, i am trying to install it to either an English or German version.

**Comment by TotalDOSCollection** [comment]
halting for the moment, but a good haul for the day.

`Renamed:Wing Commander II- Vengeance of the Kilrathi (Installer) (1991)(ORIGIN Systems, Inc.) [Action, Simulation].zip-->Wing Commander II- Vengeance of the Kilrathi v4.0 (Installer) (1991)(ORIGIN Systems, Inc.) [Action, Simulation][!].zip
Added:Wing Commander II- Vengeance of the Kilrathi v4.0 (Installer) [a1] (1991)(ORIGIN Systems, Inc.) [Action, Simulation][!].zip
Added:Wing Commander II- Vengeance of the Kilrathi v4.0 (1991)(ORIGIN Systems, Inc.) [IMA][720k].zip
Added:Wing Commander II- Vengeance of the Kilrathi v4.0 (Installer) [a2] (1991)(ORIGIN Systems, Inc.) [Action, Simulation].zip
Added:Wing Commander II- Vengeance of the Kilrathi vGE1.5F (De) (1992)(ORIGIN Systems, Inc.) [IMA][1440k].zip
Added:Wing Commander II- Vengeance of the Kilrathi vGE1.5F (Installer) (De) [a1] (1992)(ORIGIN Systems, Inc.) [Action, Simulation].zip
Added:Wing Commander II- Vengeance of the Kilrathi vGE1.7F (De) (1992)(ORIGIN Systems, Inc.) [IMA][1200k].zip
Added:Wing Commander II- Vengeance of the Kilrathi vGE1.7F (Installer) (De) (1992)(ORIGIN Systems, Inc.) [Action, Simulation].zip
Renamed:Wing Commander II- Vengeance of the Kilrathi - Special Operations 1 (1991)(ORIGIN Systems, Inc.) [kfx][1440k][!].zip-->Wing Commander II- Vengeance of the Kilrathi - Special Operations 1 vF1.3 (1991)(ORIGIN Systems, Inc.) [kfx][1440k][!].zip
Renamed:Wing Commander II- Vengeance of the Kilrathi - Special Operations 1 (1991)(ORIGIN Systems, Inc.) [IMA][1440k][!].zip-->Wing Commander II- Vengeance of the Kilrathi - Special Operations 1 vF1.3 (1991)(ORIGIN Systems, Inc.) [IMA][1440k][!].zip
Renamed:Wing Commander II- Vengeance of the Kilrathi - Special Operations 1 (1991)(ORIGIN Systems, Inc.) [Addon].zip-->Wing Commander II- Vengeance of the Kilrathi - Special Operations 1 vF1.3 (Installer) (1991)(ORIGIN Systems, Inc.) [Action, Simulation, Addon][!].zip
Added:Wing Commander II- Vengeance of the Kilrathi - Special Operations 1 vF1.4 (1991)(ORIGIN Systems, Inc.) [IMA][720k].zip
Added:Wing Commander II- Vengeance of the Kilrathi - Special Operations 1 vF1.4 (Installer) (1991)(ORIGIN Systems, Inc.) [Action, Simulation, Addon].zip
Added:Wing Commander II- Vengeance of the Kilrathi - Special Operations 1 vF1.3 (1991)(ORIGIN Systems, Inc.) [IMA][1200k].zip
Added:Wing Commander II- Vengeance of the Kilrathi - Special Operations 1 vF1.3 (Installer) [a1] (1991)(ORIGIN Systems, Inc.) [Action, Simulation, Addon].zip
Added:Wing Commander II- Vengeance of the Kilrathi - Deluxe Edition (1992)(ORIGIN Systems, Inc.) [bin-cue].zip
Added:Wing Commander II- Vengeance of the Kilrathi - Deluxe Edition (1992)(ORIGIN Systems, Inc.) [Action, Simulation, Compilation].zip
Added:Wing Commander - Wing Commander II (Special CD-ROM Edition) (1994)(ORIGIN Systems, Inc.) [bin-cue].zip
Added:Wing Commander - Wing Commander II (Special CD-ROM Edition) (1994)(ORIGIN Systems, Inc.) [Action, Simulation, Compilation].zip
`

**Comment by TotalDOSCollection** [comment]
man, I do not like code comments here. super incompatible with our update log.  I think it chokes on cr/lf combos and think neither applies?
edit, ok this one looks better than the one above.  whaddidido different?

```
Added:Wing Commander II- Vengeance of the Kilrathi - Special Operations 1 vFR1.3F (Fr) [b1] (1992)(ORIGIN Systems, Inc.) [IMA][1440k].zip
Added:Wing Commander II- Vengeance of the Kilrathi - Special Operations 1 vFR1.3F (Installer) (Fr) [b1] (1992)(ORIGIN Systems, Inc.) [Action, Simulation, Addon].zip
Added:Wing Commander II- Vengeance of the Kilrathi - Speech Accessory Pack (1991)(ORIGIN Systems, Inc.) [IMA][1200k].zip
Added:Wing Commander II- Vengeance of the Kilrathi - Speech Accessory Pack (Installer) [a1] (1991)(ORIGIN Systems, Inc.) [Action, Simulation, Addon].zip
Renamed:Wing Commander II- Vengeance of the Kilrathi - Speech Accessory Pack (1991)(ORIGIN Systems, Inc.) [Addon].zip-->Wing Commander II- Vengeance of the Kilrathi - Speech Accessory Pack (Installer) (1991)(ORIGIN Systems, Inc.) [Action, Simulation, Addon][!].zip
Renamed:Wing Commander II- Vengeance of the Kilrathi - Special Operations 2 (1992)(ORIGIN Systems, Inc.) [kfx][1440k][!].zip-->Wing Commander II- Vengeance of the Kilrathi - Special Operations 2 v7.3F (1992)(ORIGIN Systems, Inc.) [kfx][1440k][!].zip
Renamed:Wing Commander II- Vengeance of the Kilrathi - Special Operations 2 (1992)(ORIGIN Systems, Inc.) [IMA][1440k][!].zip-->Wing Commander II- Vengeance of the Kilrathi - Special Operations 2 v7.3F (1992)(ORIGIN Systems, Inc.) [IMA][1440k][!].zip
Renamed:Wing Commander II- Vengeance of the Kilrathi - Special Operations 2 (1992)(ORIGIN Systems, Inc.) [Simulation, Addon][!].zip-->Wing Commander II- Vengeance of the Kilrathi - Special Operations 2 v7.3F (Installer) (1992)(ORIGIN Systems, Inc.) [Action, Simulation, Addon][!].zip
Added:Wing Commander II- Vengeance of the Kilrathi - Special Operations 2 v7.0F (Installer) (1992)(ORIGIN Systems, Inc.) [Action, Simulation, Addon].zip
```
* Wing Commander II- Vengeance of the Kilrathi - Special Operations 1 v1.3F (Installer) (1991)(ORIGIN Systems, Inc.) [Action, Simulation, Addon][!].zip - sourced from known good kfx/ima set, 2x1.44mb. Only disk 1's volume label extracted here as the other disk is identical in name but differ in timestamp, so it would have to be renamed or separated by disk number somehow to include with very little value add.
* Wing Commander II- Vengeance of the Kilrathi - Special Operations 1 vFR1.3F (Installer) (Fr) [b1] (1992)(ORIGIN Systems, Inc.) [Action, Simulation, Addon].zip - sourced from tgod IMA, bad.  Corrupt files and cannot be fully repaired using files from other dumps.  Here only for tracking purposes.
* Wing Commander II- Vengeance of the Kilrathi - Speech Accessory Pack (Installer) [a1] (1991)(ORIGIN Systems, Inc.) [Action, Simulation, Addon].zip - sourced from IMA, 3x1.2mb Only disk 1's volume label extracted here as the other disk is identical in name but differ in timestamp, so it would have to be renamed or separated by disk number somehow to include with very little value add.
* Wing Commander II- Vengeance of the Kilrathi - Speech Accessory Pack (Installer) (1991)(ORIGIN Systems, Inc.) [Action, Simulation, Addon][!].zip - sourced from known good kfx/ima, 3x1.44 Only disk 1's volume label extracted here as the other disk is identical in name but differ in timestamp, so it would have to be renamed or separated by disk number somehow to include with very little value add.
* Wing Commander II- Vengeance of the Kilrathi - Special Operations 2 v7.3F (Installer) (1992)(ORIGIN Systems, Inc.) [Action, Simulation, Addon][!].zip - sourced from known good kfx/ima, 2x1.44mb. Only volume 1's disk label added here as the other disk is identical in name but differ in timestamp, so it would have to be renamed or separated by disk number somehow to include with very little value add.
* Wing Commander II- Vengeance of the Kilrathi - Special Operations 2 v7.0F (Installer) (1992)(ORIGIN Systems, Inc.) [Action, Simulation, Addon].zip - source unknown, likely 4x720k
* Wing Commander II- Vengeance of the Kilrathi - Special Operations 1 vF1.4 (1991)(ORIGIN Systems, Inc.) [IMA][720k].zip - this is tgod 0920
* Wing Commander II- Vengeance of the Kilrathi - Special Operations 1 vFR1.3F (Fr) [b1] (1992)(ORIGIN Systems, Inc.) [IMA][1440k].zip - this is TGOD#0414.  corrupt files, fails to install.  Best available dump, only here for tracking.

I think this finishes the job.  I have not traversed my own local storage to check for additional material yet.
